1.Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]

In [1]:
def list_to_string(files_name,dir_path):
    fileobj = open(str(dir_path)+'/'+str(files_name))
    lst = fileobj.readlines()
    new_str = ''
    for i in lst:
        new_str = new_str + i
    return new_str

In [2]:
import os
import hashlib
dirpath = input("Enter the path: ")

files = []
hashes = []
duplicate = []
i=0
count = 0
for (dir_path,dir_names,files_name) in os.walk(dirpath):
    files.extend(files_name)
    # Seeing through the contents of each file
    for i in range(len(files_name)):
        m=list_to_string(files_name[i],dir_path)
        new_hash = hashlib.sha256(m.encode())
        if str(new_hash.hexdigest()) not in hashes:
            hashes.append(str(new_hash.hexdigest()))
        else:
            duplicate.append(files_name[i])
            #os.remove(files_name[i])
            count+=1
        #print(new_hash.hexdigest())
print("Duplicate Files:",duplicate)

Enter the path: D:/Training
Duplicate Files: ['DOCs.txt']


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [3]:
import random
import string
upper = string.ascii_uppercase
lower = string.ascii_lowercase
digits = string.digits
punctuations = string.punctuation
pwd = list()
final = ''
total = 5
#print(upperCase,lowerCase,digitsCase)
pwd.append(random.choice(upper))
for i in range(2):
    pwd.append(random.choice(lower))
total-=2
for i in range(2):
    pwd.append(random.choice(digits))
total-=2
pwd.append(random.choice(punctuations))

random.shuffle(pwd)
for i in pwd:
    final = final+i
print(final)

Yk@x13


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.
[ 0 1 2 3
  4 5 6 7
  8 9 10 11 ] 
  Ans :
 [ 0 1 8 27
   4 125 6 ...]

In [4]:
import numpy as np
def create_array(i,j):
    array = np.arange(i*j,dtype='int32')
    array.resize(i,j)
    return array

arr=create_array(3,4)

In [5]:
import math
def prime(i):
    if i<2:
        return True
    for a in range(2,i):
        if i%a==0:
            return False
    return True

In [6]:
for i in range(len(arr)):
    for j in range(len(arr[0])):
        if prime(arr[i][j]):
            arr[i][j] = arr[i][j]**3
print(arr)

[[   0    1    8   27]
 [   4  125    6  343]
 [   8    9   10 1331]]


4. Python program to get the sum of every cubed value and its previous integer. 

In [7]:
arr = create_array(3,4)
new_arr = arr.copy()

for i in range(len(arr)):
    for j in range(len(arr[0])):
        if prime(arr[i][j]):
            new_arr[i][j] = new_arr[i][j]**3

final = new_arr.copy()
for i in range(len(arr)):
    for j in range(len(arr[0])):
        if prime(arr[i][j]):
            if j>0:
                final[i][j] = final[i][j] + new_arr[i][j-1]
print(final)

[[   0    1    9   35]
 [   4  129    6  349]
 [   8    9   10 1341]]


5. Given two arrays, find their intersection. Examples:
Input:  arr1[] = [1, 3, 4, 5, 7]
        arr2[] = [2, 3, 5, 6]


In [8]:
arr1 = [1,3,4,5,7]
arr2 = [2,3,5,6]
set1= set(arr1)
set2= set(arr2)
print(list(set1.intersection(arr2)))

[3, 5]


6.Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [9]:
twoD7arr = np.arange(0,7**3,7)
twoD7arr.resize(7,7)
print(twoD7arr)

[[  0   7  14  21  28  35  42]
 [ 49  56  63  70  77  84  91]
 [ 98 105 112 119 126 133 140]
 [147 154 161 168 175 182 189]
 [196 203 210 217 224 231 238]
 [245 252 259 266 273 280 287]
 [294 301 308 315 322 329 336]]


7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]

In [10]:
checker = np.zeros(7*5,dtype='int8')
checker[0::2]=1
checker.resize(7,5)
print(checker)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


8.	Create a given Matrix:
[  A,     B,     C,       D
   E,     F,      G,      H
   I,     a,      K,      L
   M,     N,      o,      P
   Q,     R,      S,      T
   U,     0,     W,       O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values

In [13]:
lst = [['A','B','C','D'],['E','F','G','H'],['I','a','K','L'],['M','N','o','P'],['Q','R','S','T'],['U','0','W','O']]
vowels = ['A','a','E','e','I','i','O','o','U','u']
alphaArr = np.array(lst)
alphaArr= alphaArr.flatten()
for i in range(len(vowels)):
    alphaArr = np.where(alphaArr==vowels[i], np.nan, alphaArr)
alphaArr.resize(6,4)
print(alphaArr)

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'nan' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' '0' 'W' 'nan']]
